"""urgh

Revision ID: d9a1640d756f
Revises: 53a6063b974c
Create Date: 2019-09-05 21:23:21.952629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9a1640d756f'
down_revision = '53a6063b974c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('dummy', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'dummy')
    # ### end Alembic commands ###
